# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('balance', models.FloatField(max_length=100)),
                ('pin_code', models.CharField(max_length=4)),
                ('availability', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('total', models.FloatField(max_length=100)),
            ],
        ),
    ]
