# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 18:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 14, 18, 45, 35, 94000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankcard',
            name='max_balance',
            field=models.FloatField(default=10000, max_length=100),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='user_access',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='was_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
