# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0002_auto_20160414_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[(b'WD', b'Writing down'), (b'R', b'Refill'), (b'O', b'Other')], max_length=2)),
                ('balance_before', models.FloatField(max_length=100)),
                ('balance_after', models.FloatField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representation.BankCard')),
            ],
        ),
    ]
