# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0003_cardhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='max_balance',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='balance_after',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='balance_before',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investor',
            name='total',
            field=models.IntegerField(),
        ),
    ]
