# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0004_auto_20160422_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='operation',
            field=models.CharField(choices=[(b'Writing down', b'WD'), (b'Refill', b'R'), (b'Other', b'O')], max_length=20),
        ),
    ]
