# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0005_auto_20160427_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='operation',
            field=models.CharField(choices=[(b'WD', b'Writing down'), (b'R', b'Refill'), (b'O', b'Other')], max_length=20),
        ),
    ]
