# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0006_auto_20160427_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=15)),
            ],
        ),
    ]
