# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0006_auto_20160427_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
