# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representation', '0006_auto_20160427_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
